services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: wallet_db
    ports:
      - '3010:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: